language: node_js
git:
  depth: 1
  quiet: true
  submodules: false
  clone: false
  symlinks: true
  autocrlf: input
branches:
  only:
    - master
install:
  - npm install
script:
  - npm run build
  - npm run cypress:open
node_js:
  - node
  - 14
cache: npm
env:
  - DB=postgres
  - SH=bash
  - PACKAGE_VERSION="1.0.*"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
#密码：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
