language: node_js
git:
  depth: 1
  quiet: true
  submodules: false
  clone: false
  symlinks: true
  autocrlf: input
branches:
  only:
    - master
install:
  - npm install
  - npm run cypress:open
script:
  - npm run build
node_js:
  - node
  - 14
cache: npm
env:
  - DB=postgres
  - SH=bash
  - PACKAGE_VERSION="1.0.*"
